# Generated by Django 6.0.6 on 2026-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonstat',
            name='calculated_per',
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='blocks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='fg_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='fga',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='fgm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='ft_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='fta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='ftm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='steals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='three_pa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='three_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='three_pm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='turnovers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
